# Generated by Django 6.0.1 on 2026-01-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('survey', 'survey'), ('learner_activities', 'Learner Activities')], max_length=30)),
                ('source', models.CharField(default='csv', max_length=30)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='DataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', models.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('semantic_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_datasets', to='analytics.dataset')),
            ],
        ),
    ]
