# Generated by Django 6.0.1 on 2026-01-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('nps', 'NPS'), ('csat', 'CSAT'), ('distribution', 'Distribution'), ('summary', 'Summary')], max_length=30)),
                ('dimension', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dataset')),
            ],
        ),
    ]
