# Generated by Django 6.0.1 on 2026-01-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_insight'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcolumn',
            name='semantic_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='datasetcolumn',
            unique_together={('dataset', 'raw_name')},
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(fields=('cohort', 'dataset_type'), name='unique_dataset_per_cohort_type'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash', None), _negated=True), fields=('file_hash',), name='unique_file_hash'),
        ),
    ]
