# Generated by Django 6.0.1 on 2026-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_dataset_unique_dataset_per_cohort_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('nps', 'NPS'), ('csat', 'CSAT'), ('distribution', 'Distribution'), ('summary', 'Summary'), ('ai_summary', 'AI Summary')], max_length=30),
        ),
    ]
