# Generated by Django 6.0.1 on 2026-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_dataset_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcolumn',
            name='semantic_type',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
